# id $Id$
# author $Author$
# version $Revision$
# lastrevision $Date$
# modifiedby $LastChangedBy$
# lastmodified $LastChangedDate$


ROOTACT ?= $(shell cd .. && pwd)
SUBDIRS = unitTest xpath libinterv2 astro cal waveGen addtime bin mxml beremiz.addons timerFB validation interv2

include $(ROOTACT)/Makefile.common.recurse

