/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actility_m2m_xo_jni_JniXo */

#ifndef _Included_com_actility_m2m_xo_jni_JniXo
#define _Included_com_actility_m2m_xo_jni_JniXo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    init
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_init
  (JNIEnv *, jclass);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    start
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_xo_jni_JniXo_start
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_stop
  (JNIEnv *, jclass);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    isBinarySupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_xo_jni_JniXo_isBinarySupported
  (JNIEnv *, jclass);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    isXmlSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_xo_jni_JniXo_isXmlSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    isExiSupported
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_xo_jni_JniXo_isExiSupported
  (JNIEnv *, jclass);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmType
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmType
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoLoadMem
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoLoadMem
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadXmlMem
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadXmlMem
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadPartialXmlMem
 * Signature: ([BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadPartialXmlMem
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadExiMem
 * Signature: ([BZ)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadExiMem
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadPartialExiMem
 * Signature: ([BLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadPartialExiMem
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmNew
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmNew
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNewCopy
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNewCopy
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoSetNameSpace
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoSetNameSpace
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoUnSetNameSpace
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoUnSetNameSpace
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferBinaryToXml
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferBinaryToXml
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferBinaryToExi
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferBinaryToExi
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferXmlToBinary
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferXmlToBinary
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferXmlToExi
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferXmlToExi
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferExiToBinary
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferExiToBinary
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferExiToXml
 * Signature: (ILjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferExiToXml
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWriteXmlMem
 * Signature: (ILjava/lang/String;Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWriteXmlMem
  (JNIEnv *, jclass, jint, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWritePartialXmlMem
 * Signature: (ILjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWritePartialXmlMem
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWriteExiMem
 * Signature: (IZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWriteExiMem
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWritePartialExiMem
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWritePartialExiMem
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoSaveMem
 * Signature: (I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoSaveMem
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmContainsAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmContainsAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmGetAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmGetAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmGetAttr
 * Signature: (ILjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmGetAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoBufferNmGetAttr
 * Signature: (ILjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoBufferNmGetAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmSetAttr
 * Signature: (ILjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmSetAttr
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmSetAttr
 * Signature: (ILjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmSetAttr
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoBufferNmSetAttr
 * Signature: (ILjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoBufferNmSetAttr
  (JNIEnv *, jclass, jint, jstring, jbyteArray);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmUnSetAttr
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmUnSetAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmAddInAttr
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmAddInAttr
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmAddInAttr
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmAddInAttr
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmIndexOf
 * Signature: (ILjava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmIndexOf
  (JNIEnv *, jclass, jint, jstring, jint);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmIndexOf
 * Signature: (ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmIndexOf
  (JNIEnv *, jclass, jint, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmNbInAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmNbInAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmFirstAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmFirstAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmNextAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmNextAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmLastAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmLastAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmSupInAttr
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmSupInAttr
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmDropList
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmDropList
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoFree
 * Signature: (IZ)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoFree
  (JNIEnv *, jclass, jint, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmType64
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmType64
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoLoadMem64
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoLoadMem64
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadXmlMem64
 * Signature: ([BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadXmlMem64
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadPartialXmlMem64
 * Signature: ([BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadPartialXmlMem64
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadExiMem64
 * Signature: ([BZ)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadExiMem64
  (JNIEnv *, jclass, jbyteArray, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoReadPartialExiMem64
 * Signature: ([BLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoReadPartialExiMem64
  (JNIEnv *, jclass, jbyteArray, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmNew64
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmNew64
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNewCopy64
 * Signature: (JZ)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNewCopy64
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoSetNameSpace64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoSetNameSpace64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoUnSetNameSpace64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoUnSetNameSpace64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferBinaryToXml64
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferBinaryToXml64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferBinaryToExi64
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferBinaryToExi64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferXmlToBinary64
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferXmlToBinary64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferXmlToExi64
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferXmlToExi64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferExiToBinary64
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferExiToBinary64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmXoBufferExiToXml64
 * Signature: (JLjava/lang/String;Z)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmXoBufferExiToXml64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWriteXmlMem64
 * Signature: (JLjava/lang/String;Z)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWriteXmlMem64
  (JNIEnv *, jclass, jlong, jstring, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWritePartialXmlMem64
 * Signature: (JLjava/lang/String;Ljava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWritePartialXmlMem64
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWriteExiMem64
 * Signature: (JZ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWriteExiMem64
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoWritePartialExiMem64
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoWritePartialExiMem64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoSaveMem64
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoSaveMem64
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmContainsAttr64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmContainsAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmGetAttr64
 * Signature: (JLjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmGetAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmGetAttr64
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmGetAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoBufferNmGetAttr64
 * Signature: (JLjava/lang/String;)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoBufferNmGetAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmSetAttr64
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmSetAttr64
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmSetAttr64
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmSetAttr64
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoBufferNmSetAttr64
 * Signature: (JLjava/lang/String;[B)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoBufferNmSetAttr64
  (JNIEnv *, jclass, jlong, jstring, jbyteArray);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmUnSetAttr64
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmUnSetAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmAddInAttr64
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmAddInAttr64
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmAddInAttr64
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmAddInAttr64
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoObjectNmIndexOf64
 * Signature: (JLjava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoObjectNmIndexOf64
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoStringNmIndexOf64
 * Signature: (JLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoStringNmIndexOf64
  (JNIEnv *, jclass, jlong, jstring, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmNbInAttr64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmNbInAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmFirstAttr64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmFirstAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmNextAttr64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmNextAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmLastAttr64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmLastAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmSupInAttr64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmSupInAttr64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoNmDropList64
 * Signature: (JLjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoNmDropList64
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoFree64
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoFree64
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_actility_m2m_xo_jni_JniXo
 * Method:    xoDumpNbOcc
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_xo_jni_JniXo_xoDumpNbOcc
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
