# id $Id$
# author $Author$
# version $Revision$
# lastrevision $Date$
# modifiedby $LastChangedBy$
# lastmodified $LastChangedDate$


ROOTACT ?= $(shell cd .. && pwd)
SUBDIRS = include xoref lib tictools supervisor tunslip snif

include $(ROOTACT)/Makefile.common.recurse

