/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actility_m2m_song_binding_coap_jni_impl_DiaJni */

#ifndef _Included_com_actility_m2m_song_binding_coap_jni_impl_DiaJni
#define _Included_com_actility_m2m_song_binding_coap_jni_impl_DiaJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;I)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaInit
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jint);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaTrace
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaTrace
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaPrepare
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaPrepare
  (JNIEnv *, jobject);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaRun
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaRun
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaEnterCS
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaEnterCS
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaLeaveCS
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaLeaveCS
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaCreateResponse
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BLjava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaCreateResponse
  (JNIEnv *, jobject, jlong, jstring, jstring, jbyteArray, jstring, jobjectArray, jint, jstring);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaRetrieveResponse
 * Signature: (JLjava/lang/String;[BLjava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaRetrieveResponse
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jstring, jobjectArray, jint, jstring);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaUpdateResponse
 * Signature: (JLjava/lang/String;[BLjava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaUpdateResponse
  (JNIEnv *, jobject, jlong, jstring, jbyteArray, jstring, jobjectArray, jint, jstring);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaDeleteResponse
 * Signature: (JLjava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaDeleteResponse
  (JNIEnv *, jobject, jlong, jstring, jobjectArray, jint, jstring);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaCreateRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BLjava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaCreateRequest
  (JNIEnv *, jobject, jlong, jstring, jstring, jbyteArray, jstring, jobjectArray, jobjectArray);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaRetrieveRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaRetrieveRequest
  (JNIEnv *, jobject, jlong, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaUpdateRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;[BLjava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaUpdateRequest
  (JNIEnv *, jobject, jlong, jstring, jstring, jbyteArray, jstring, jobjectArray, jobjectArray);

/*
 * Class:     com_actility_m2m_song_binding_coap_jni_impl_DiaJni
 * Method:    diaDeleteRequest
 * Signature: (JLjava/lang/String;Ljava/lang/String;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;[Lcom/actility/m2m/song/binding/coap/ni/api/DiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_coap_jni_impl_DiaJni_diaDeleteRequest
  (JNIEnv *, jobject, jlong, jstring, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
