#!/bin/bash

ASTYLE_OPTIONS="--style=ansi --indent=spaces=2 --indent-classes --indent-switches "
ASTYLE_OPTIONS=$ASTYLE_OPTIONS"--pad-oper --pad-header --add-brackets --convert-tabs "
ASTYLE_OPTIONS=$ASTYLE_OPTIONS"--align-pointer=name --align-reference=name "
ASTYLE_OPTIONS=$ASTYLE_OPTIONS"--lineend=linux --max-instatement-indent=2 "

if [ -z "$ROOTACT" ]
then
	echo "ROOTACT not specified" >&2
	exit 1
fi
source $ROOTACT/rtbase/base/system

SELF=wmbus
echo "#####"
echo	"$SELF for $SYSTEM"

Compile()
{
  if which astyle 2> /dev/null
  then
    astyle $ASTYLE_OPTIONS lib/*.h lib/*.c supervisor/*.h supervisor/*.c
  fi
  for i in base include lib supervisor xoref _test_*
  do
	  (
    if [ -d "$i" ]
    then
    	cd $i
	    if [ -f MAKE ]
  	  then
  	  	echo "#####"
	  	  echo "#####	$i"
  	  	echo "#####"
	  	  sh ./MAKE $*
    	fi
    fi
	  )
    if [ $? -ne 0 ]
    then
      exit 1
    fi
  done
}

# frequemment oublié dans les makefile
CleanPlus()
{	
	rm -f */core.* > /dev/null 2>&1
	rm -f */core > /dev/null 2>&1
	rm -f */TRACE_* > /dev/null 2>&1
	rm -f */*.log > /dev/null 2>&1
}

Test()
{

  echo "   _____       _"
  echo "  |_   _|__ __| |_ ___"
  echo "    | |/ -_|_-<  _(_-<"
  echo "    |_|\\___/__/\\__/__/"
  echo

  for testDir in _test_*
  do
    pushd .
    cd $testDir
    for test in *.x
    do
      if ! [ -x $test ] || ! eval "PATH=. $test"
      then
        exit 1
      fi
    done
    popd
  done

  echo "     _   _ _   _          _                                 _"
  echo "    /_\\ | | | | |_ ___ __| |_ ___  ____  _ __ __ ___ ___ __| |"
  echo "   / _ \\| | | |  _/ -_|_-<  _(_-< (_-< || / _/ _/ -_) -_) _\` |"
  echo "  /_/ \\_\\_|_|  \\__\\___/__/\\__/__/ /__/\\_,_\\__\\__\\___\\___\\__,_|"
  echo

}

Documentation()
{
  echo "   ___                             _        _   _"
  echo "  |   \\ ___  __ _  _ _ __  ___ _ _| |_ __ _| |_(_)___ _ _"
  echo "  | |) / _ \\/ _| || | '  \\/ -_) ' \\  _/ _\` |  _| / _ \\ ' \\"
  echo "  |___/\\___/\\__|\\_,_|_|_|_\\___|_||_\\__\\__,_|\\__|_\\___/_||_|"
  echo
  VERSION=`cat Version`
  sed -i -e 's/PROJECT_NUMBER.*=.*/PROJECT_NUMBER = '$VERSION'/' doc/wmbus.Doxyfile
  doxygen doc/wmbus.Doxyfile
}

case  $# in
	0)
		Compile
		exit 0
		;;
	*)	case $1 in
			src|source)
				shift
				MAKE clean
				sh ${MKPKGSOURCE} -p $SELF $*
				exit 0
			;;
			runtime)
				shift
				MAKE
				sh ${MKPKGRUNTIME} -p $SELF
				exit 0
			;;
			clean)
				shift
				CleanPlus
				Compile clean
				exit 0
				;;
      test)
        shift
        CleanPlus
        Compile clean
        Compile
        Test
        exit 0
      ;;
      doc)
        shift
        Documentation
        exit 0
      ;;
			*)
				Compile $*
				exit 0
				;;
		esac
	;;
esac

echo "Usage: MAKE [clean|runtime|src|source|test|doc]"
exit 1

