/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class diajni */

#ifndef _Included_diajni
#define _Included_diajni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     diajni
 * Method:    diaInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_diajni_diaInit
  (JNIEnv *, jobject);

/*
 * Class:     diajni
 * Method:    diaPoll
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_diajni_diaPoll
  (JNIEnv *, jobject);

/*
 * Class:     diajni
 * Method:    diaRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_diajni_diaRun
  (JNIEnv *, jobject);

/*
 * Class:     diajni
 * Method:    diaStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_diajni_diaStop
  (JNIEnv *, jobject);

/*
 * Class:     diajni
 * Method:    diaFree
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_diajni_diaFree
  (JNIEnv *, jobject);

/*
 * Class:     diajni
 * Method:    diaCreateResponse
 * Signature: (Ljava/lang/String;Ljava/lang/String;[BLjava/lang/String;[LdiaOpt;I)V
 */
JNIEXPORT void JNICALL Java_diajni_diaCreateResponse
  (JNIEnv *, jobject, jstring, jstring, jbyteArray, jstring, jobjectArray, jint);

/*
 * Class:     diajni
 * Method:    diaRetrieveResponse
 * Signature: (Ljava/lang/String;[BLjava/lang/String;[LdiaOpt;I)V
 */
JNIEXPORT void JNICALL Java_diajni_diaRetrieveResponse
  (JNIEnv *, jobject, jstring, jbyteArray, jstring, jobjectArray, jint);

/*
 * Class:     diajni
 * Method:    diaUpdateResponse
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[LdiaOpt;I)V
 */
JNIEXPORT void JNICALL Java_diajni_diaUpdateResponse
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jint);

/*
 * Class:     diajni
 * Method:    diaDeleteResponse
 * Signature: (Ljava/lang/String;[LdiaOpt;I)V
 */
JNIEXPORT void JNICALL Java_diajni_diaDeleteResponse
  (JNIEnv *, jobject, jstring, jobjectArray, jint);

/*
 * Class:     diajni
 * Method:    diaCreateRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[LdiaOpt;[LdiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_diajni_diaCreateRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     diajni
 * Method:    diaRetrieveRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;[LdiaOpt;[LdiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_diajni_diaRetrieveRequest
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     diajni
 * Method:    diaUpdateRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[LdiaOpt;[LdiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_diajni_diaUpdateRequest
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jobjectArray, jobjectArray);

/*
 * Class:     diajni
 * Method:    diaDeleteRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;[LdiaOpt;[LdiaOpt;)I
 */
JNIEXPORT jint JNICALL Java_diajni_diaDeleteRequest
  (JNIEnv *, jobject, jstring, jstring, jobjectArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
