include $(ROOTACT)/rtbase/base/makefile.def

KNXLIB= $(ROOTACT)/knx/lib/libknx.a

INC = -I$(ROOTACT)/ \
      -I$(ROOTACT)/xo/include \
      -I$(ROOTACT)/drvcommon/lib \
      -I$(ROOTACT)/libdIa \
      -I$(ROOTACT)/libcoap \
      -I$(ROOTACT)/knx/include \
      -I$(ROOTACT)/knx/lib \
      -I$(ROOTACT)/knx/supervisor \
      -I$(ROOTACT)/include \
      $(DEFINC)

LDPATH = -L$(ROOTACT)/shlib \
         -L$(ROOTACT)/lib

SHLIB = -lpthread -lrt -leibclient -lrtbase -lxo -ldrvcommon -ldIa 

# Add version define
CCFLAGS += -D__KNX_DRIVER_VERSION__=`cat $(ROOTACT)/knx/Version`
