
CCFLAGS += -Wall -Werror
ifeq ($(DEBUG),on)
  CCFLAGS += -g -O0
endif

ifeq ($(SIZE_OPTIM),on)
  CCFLAGS = -Wall -Werror -Os
endif

ifeq ($(NO_TRACE),on)
  CCFLAGS += -D__NO_TRACE__
endif

INVT="\\033[7m" 
NORM="\\033[0m" 
BOLD="\\033[1m" 
BLINK="\\033[5m"

