# id $Id$
# author $Author$
# version $Revision$
# lastrevision $Date$
# modifiedby $LastChangedBy$
# lastmodified $LastChangedDate$


ROOTACT ?= $(shell cd ../../.. && pwd)
SUBDIRS = extension1 extension2 extension3

include $(ROOTACT)/Makefile.common.recurse

