/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actility_m2m_song_binding_http_jni_impl_JHttpClients */

#ifndef _Included_com_actility_m2m_song_binding_http_jni_impl_JHttpClients
#define _Included_com_actility_m2m_song_binding_http_jni_impl_JHttpClients
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    httpClientsInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_httpClientsInit
  (JNIEnv *, jobject);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    httpClientsRun
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_httpClientsRun
  (JNIEnv *, jobject);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    httpClientsStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_httpClientsStop
  (JNIEnv *, jobject);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setTraceLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setTraceLevel
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    createHttpClient
 * Signature: (Z)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_createHttpClient
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setProxyCredentials
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setProxyCredentials
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setProxy
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setProxy
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setMaxSocketsPerHost
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setMaxSocketsPerHost
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setMaxTotalSockets
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setMaxTotalSockets
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setTcpNoDelay
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setTcpNoDelay
  (JNIEnv *, jobject, jlong, jboolean);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setRequestTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setRequestTimeout
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setConnectionTimeout
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setConnectionTimeout
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    dumpPendingTransactions
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_dumpPendingTransactions
  (JNIEnv *, jobject);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    createTransaction
 * Signature: (JLjava/lang/Object;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_createTransaction
  (JNIEnv *, jobject, jlong, jobject, jstring, jstring, jstring);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    releaseTransaction
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_releaseTransaction
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    addRequestHeader
 * Signature: (JLjava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_addRequestHeader
  (JNIEnv *, jobject, jlong, jstring, jstring);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setRequestBody
 * Signature: (J[B)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setRequestBody
  (JNIEnv *, jobject, jlong, jbyteArray);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    setRequestProxy
 * Signature: (JLjava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_setRequestProxy
  (JNIEnv *, jobject, jlong, jstring, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    sendRequest
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_sendRequest
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getResponseStatusCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getResponseStatusCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getResponseRawStatusCode
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getResponseRawStatusCode
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getResponseReasonPhrase
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getResponseReasonPhrase
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getResponseHeader
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getResponseHeader
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getNthResponseHeaderName
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getNthResponseHeaderName
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getNthResponseHeaderValue
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getNthResponseHeaderValue
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getResponseContentLength
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getResponseContentLength
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getResponseBody
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getResponseBody
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getRemoteAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getRemoteAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getRemotePort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getRemotePort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getLocalAddress
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getLocalAddress
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getLocalPort
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getLocalPort
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_actility_m2m_song_binding_http_jni_impl_JHttpClients
 * Method:    getProtocol
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_actility_m2m_song_binding_http_jni_impl_JHttpClients_getProtocol
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
