#!/bin/bash

ARGS=$*

ASTYLE_OPTIONS="--style=ansi --indent=spaces=2 --indent-classes --indent-switches "
ASTYLE_OPTIONS=$ASTYLE_OPTIONS"--pad-oper --pad-header --add-brackets --convert-tabs "
ASTYLE_OPTIONS=$ASTYLE_OPTIONS"--align-pointer=name --align-reference=name "
ASTYLE_OPTIONS=$ASTYLE_OPTIONS"--lineend=linux --max-instatement-indent=2 "

if which astyle 2> /dev/null
then
  astyle $ASTYLE_OPTIONS manufacturer_*/*.h manufacturer_*/*.c
fi
for i in manufacturer_*
do
 (
  if [ -d "$i" ]
  then
  	cd $i
 	  echo "#####"
  	echo "#####	$i"
 	  echo "#####"
    make $ARGS
  fi
  )
  if [ $? -ne 0 ]
  then
    exit 1
  fi
done


