
#ifndef _COMMON__H_
#define _COMMON__H_

#define MAX_BUF_SIZE_XS 32
#define MAX_BUF_SIZE_S 127
#define MAX_BUF_SIZE_B 255
#define MAX_BUF_SIZE_H 1023
#define MAX_BUF_SIZE_VL 2047

#define HEADER_CONTENT_LENGTH "Content-Length"
#define HEADER_CONTENT_TYPE "Content-Type"
#define HEADER_CONTENT_LOCATION "Content-Location"
#define HEADER_EXPECT "Expect"
#define HEADER_TRANSFER_ENCODING "Transfer-Encoding"
#define HEADER_AUTHORIZATION "Authorization"

#define METHOD_DELETE "DELETE"

#define DEFAULT_HTTPCLIENT_MAX_CONNECTS 5
#define DEFAULT_HTTPCLIENT_PIPELINE 0L
#define DEFAULT_TRANSACTION_CONNECT_TIMEOUT 10000L
#define DEFAULT_TRANSACTION_TIMEOUT 32000L

#define SOH_STATUS_BAD_REQUEST "STATUS_BAD_REQUEST"
#define SOH_STATUS_NOT_FOUND "STATUS_METHOD_NOT_FOUND"
#define SOH_STATUS_METHOD_NOT_ALLOWED "STATUS_METHOD_NOT_ALLOWED"

#define SOH_STATUS_UNAVAILABLE "STATUS_SERVICE_UNAVAILABLE"
#define SOH_STATUS_NOT_IMPLEMENTED "STATUS_NOT_IMPLEMENTED"
#define SOH_STATUS_GATEWAY_TIMEOUT "STATUS_GATEWAY_TIMEOUT"


typedef enum _SOH_METHOD {
  SOH_UNKNOWN = 0,
  SOH_CREATE,
  SOH_RETRIEVE,
  SOH_UPDATE,
  SOH_DELETE,
} SOH_METHOD;

// trace levels
enum
{
  TRACE_FATAL = 0,
  TRACE_ERROR = 1,
  TRACE_WARN = 2,
  TRACE_INFO = 3,
  TRACE_DEBUG = 4,
  TRACE_TRACE = 5,
};


#endif
