/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 * 
 * This file is not intended to be easily readable and contains a number of 
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG 
 * interface file instead. 
 * ----------------------------------------------------------------------------- */

#define SWIGJAVA

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__)) 
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__)) 
# else
#   define SWIGUNUSED 
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif 
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED 
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#  ifndef GCC_HASCLASSVISIBILITY
#    define GCC_HASCLASSVISIBILITY
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif 
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif



/* Fix for jlong on some versions of gcc on Windows */
#if defined(__GNUC__) && !defined(__INTEL_COMPILER)
  typedef long long __int64;
#endif

/* Fix for jlong on 64-bit x86 Solaris */
#if defined(__x86_64)
# ifdef _LP64
#   undef _LP64
# endif
#endif

#include <jni.h>
#include <stdlib.h>
#include <string.h>


/* Support for throwing Java exceptions */
typedef enum {
  SWIG_JavaOutOfMemoryError = 1, 
  SWIG_JavaIOException, 
  SWIG_JavaRuntimeException, 
  SWIG_JavaIndexOutOfBoundsException,
  SWIG_JavaArithmeticException,
  SWIG_JavaIllegalArgumentException,
  SWIG_JavaNullPointerException,
  SWIG_JavaDirectorPureVirtual,
  SWIG_JavaUnknownError
} SWIG_JavaExceptionCodes;

typedef struct {
  SWIG_JavaExceptionCodes code;
  const char *java_exception;
} SWIG_JavaExceptions_t;


static void SWIGUNUSED SWIG_JavaThrowException(JNIEnv *jenv, SWIG_JavaExceptionCodes code, const char *msg) {
  jclass excep;
  static const SWIG_JavaExceptions_t java_exceptions[] = {
    { SWIG_JavaOutOfMemoryError, "java/lang/OutOfMemoryError" },
    { SWIG_JavaIOException, "java/io/IOException" },
    { SWIG_JavaRuntimeException, "java/lang/RuntimeException" },
    { SWIG_JavaIndexOutOfBoundsException, "java/lang/IndexOutOfBoundsException" },
    { SWIG_JavaArithmeticException, "java/lang/ArithmeticException" },
    { SWIG_JavaIllegalArgumentException, "java/lang/IllegalArgumentException" },
    { SWIG_JavaNullPointerException, "java/lang/NullPointerException" },
    { SWIG_JavaDirectorPureVirtual, "java/lang/RuntimeException" },
    { SWIG_JavaUnknownError,  "java/lang/UnknownError" },
    { (SWIG_JavaExceptionCodes)0,  "java/lang/UnknownError" }
  };
  const SWIG_JavaExceptions_t *except_ptr = java_exceptions;

  while (except_ptr->code != code && except_ptr->code)
    except_ptr++;

  (*jenv)->ExceptionClear(jenv);
  excep = (*jenv)->FindClass(jenv, except_ptr->java_exception);
  if (excep)
    (*jenv)->ThrowNew(jenv, excep, msg);
}


/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg) if (!(expr)) {SWIG_JavaThrowException(jenv, SWIG_JavaIllegalArgumentException, msg); return nullreturn; } else


  #include <sqlite3.h>
  #include <sqlite_driver.h>

 

void freeAttribute(InternalAttribute * attribute)
{
  if (attribute == NULL) return;
  //fprintf(stdout,"Free attribute %d\n",attribute);
  if (attribute->name) free(attribute->name);
  if (attribute->string_value) free(attribute->string_value);
  if (attribute->date_value) free(attribute->date_value);
  free(attribute);
}

void freeInternalAttrOperation(InternalAttrOperation * oper)
{
  if (oper == NULL) return;
  //fprintf(stdout,"Free operation %d\n",oper);
  free(oper);
}

 
void freeInternalCondition(InternalCondition * data)
{
  if (data == NULL) return;
  if (data->attributeName) free(data->attributeName);
  if (data->operand) free(data->operand);
  free(data);
}
void freeConfigItem(ConfigItem * item)
{
  if (item == NULL) return;
  if (item->key) free(item->key);
  if (item->value) free(item->value);
  free(item);
}

SWIGINTERN void delete_ConfigItem(ConfigItem *self){
    freeConfigItem(self);
  }
SWIGINTERN void delete_InternalAttribute(InternalAttribute *self){
    freeAttribute(self);
  }
SWIGINTERN void delete_InternalAttrOperation(InternalAttrOperation *self){
    freeInternalAttrOperation(self);
  }
SWIGINTERN void delete_InternalCondition(InternalCondition *self){
    freeInternalCondition(self);
  }
SWIGINTERN void delete_SearchReturn(SearchReturn *self){
    freeSearchReturn(self);
  }

static subSearchResult * *new_search_array(int nelements) { 
  return (subSearchResult * *) calloc(nelements,sizeof(subSearchResult *)); 
}

static void delete_search_array(subSearchResult * *ary) { 
  free(ary); 
}

static subSearchResult * search_array_getitem(subSearchResult * *ary, int index) {
    return ary[index];
}
static void search_array_setitem(subSearchResult * *ary, int index, subSearchResult * value) {
    ary[index] = value;
}


static InternalAttribute * *new_attribute_array(int nelements) { 
  return (InternalAttribute * *) calloc(nelements,sizeof(InternalAttribute *)); 
}

static void delete_attribute_array(InternalAttribute * *ary) { 
  free(ary); 
}

static InternalAttribute * attribute_array_getitem(InternalAttribute * *ary, int index) {
    return ary[index];
}
static void attribute_array_setitem(InternalAttribute * *ary, int index, InternalAttribute * value) {
    ary[index] = value;
}


static InternalAttrOperation * *new_operation_array(int nelements) { 
  return (InternalAttrOperation * *) calloc(nelements,sizeof(InternalAttrOperation *)); 
}

static void delete_operation_array(InternalAttrOperation * *ary) { 
  free(ary); 
}

static InternalAttrOperation * operation_array_getitem(InternalAttrOperation * *ary, int index) {
    return ary[index];
}
static void operation_array_setitem(InternalAttrOperation * *ary, int index, InternalAttrOperation * value) {
    ary[index] = value;
}


static ConfigItem * *new_configItem_array(int nelements) { 
  return (ConfigItem * *) calloc(nelements,sizeof(ConfigItem *)); 
}

static void delete_configItem_array(ConfigItem * *ary) { 
  free(ary); 
}

static ConfigItem * configItem_array_getitem(ConfigItem * *ary, int index) {
    return ary[index];
}
static void configItem_array_setitem(ConfigItem * *ary, int index, ConfigItem * value) {
    ary[index] = value;
}


static InternalCondition * *new_condition_array(int nelements) { 
  return (InternalCondition * *) calloc(nelements,sizeof(InternalCondition *)); 
}

static void delete_condition_array(InternalCondition * *ary) { 
  free(ary); 
}

static InternalCondition * condition_array_getitem(InternalCondition * *ary, int index) {
    return ary[index];
}
static void condition_array_setitem(InternalCondition * *ary, int index, InternalCondition * value) {
    ary[index] = value;
}


#ifdef __cplusplus
extern "C" {
#endif

SWIGEXPORT jchar JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_PATH_1DELIMITER_1get(JNIEnv *jenv, jclass jcls) {
  jchar jresult = 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  result = (char) '/';
  jresult = (jchar)result; 
  return jresult;
}


SWIGEXPORT jchar JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_STAR_1CHAR_1get(JNIEnv *jenv, jclass jcls) {
  jchar jresult = 0 ;
  char result;
  
  (void)jenv;
  (void)jcls;
  result = (char) '*';
  jresult = (jchar)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SCOPE_1ONE_1LEVEL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SCOPE_1SUBTREE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_NO_1LIMIT_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) -1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ORDER_1ASC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ORDER_1DESC_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ORDER_1UNKNOWN_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1EQUAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1NOT_1EQUAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1STRICTLY_1GREATER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1LOWER_1OR_1EQUAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1STRICTLY_1LOWER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1GREATER_1OR_1EQUAL_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 5;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1OP_1STARTS_1WITH_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 6;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_COND_1OP_1AND_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_COND_1OP_1OR_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SQLITE_1OK_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1TYPE_1INTEGER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1TYPE_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1TYPE_1DATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 2;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1TYPE_1LIST_1INTEGER_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 3;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1TYPE_1LIST_1STRING_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 4;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ATTR_1TYPE_1LIST_1DATE_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 5;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_TYPE_1SET_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 0;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_TYPE_1UNSET_1get(JNIEnv *jenv, jclass jcls) {
  jint jresult = 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  result = (int) 1;
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigItem_1key_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  ConfigItem *arg1 = (ConfigItem *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigItem **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->key) free((char *)arg1->key);
    if (arg2) {
      arg1->key = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->key, (const char *)arg2);
    } else {
      arg1->key = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigItem_1key_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  ConfigItem *arg1 = (ConfigItem *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigItem **)&jarg1; 
  result = (char *) ((arg1)->key);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigItem_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  ConfigItem *arg1 = (ConfigItem *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigItem **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->value) free((char *)arg1->value);
    if (arg2) {
      arg1->value = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->value, (const char *)arg2);
    } else {
      arg1->value = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigItem_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  ConfigItem *arg1 = (ConfigItem *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigItem **)&jarg1; 
  result = (char *) ((arg1)->value);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1ConfigItem(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ConfigItem *arg1 = (ConfigItem *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ConfigItem **)&jarg1; 
  delete_ConfigItem(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1ConfigItem(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ConfigItem *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ConfigItem *)calloc(1, sizeof(ConfigItem));
  *(ConfigItem **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigList_1items_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  ConfigList *arg1 = (ConfigList *) 0 ;
  ConfigItem **arg2 = (ConfigItem **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigList **)&jarg1; 
  arg2 = *(ConfigItem ***)&jarg2; 
  if (arg1) (arg1)->items = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigList_1items_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  ConfigList *arg1 = (ConfigList *) 0 ;
  ConfigItem **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigList **)&jarg1; 
  result = (ConfigItem **) ((arg1)->items);
  *(ConfigItem ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigList_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  ConfigList *arg1 = (ConfigList *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigList **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_ConfigList_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  ConfigList *arg1 = (ConfigList *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(ConfigList **)&jarg1; 
  result = (int) ((arg1)->length);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1ConfigList(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  ConfigList *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (ConfigList *)calloc(1, sizeof(ConfigList));
  *(ConfigList **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1ConfigList(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ConfigList *arg1 = (ConfigList *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ConfigList **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->name) free((char *)arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  result = (int) ((arg1)->type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1string_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->string_value) free((char *)arg1->string_value);
    if (arg2) {
      arg1->string_value = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->string_value, (const char *)arg2);
    } else {
      arg1->string_value = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1string_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  result = (char *) ((arg1)->string_value);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1int_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->int_value = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1int_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  result = (int) ((arg1)->int_value);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1date_1value_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->date_value) free((char *)arg1->date_value);
    if (arg2) {
      arg1->date_value = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->date_value, (const char *)arg2);
    } else {
      arg1->date_value = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttribute_1date_1value_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttribute **)&jarg1; 
  result = (char *) ((arg1)->date_value);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1InternalAttribute(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  InternalAttribute *arg1 = (InternalAttribute *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalAttribute **)&jarg1; 
  delete_InternalAttribute(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1InternalAttribute(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  InternalAttribute *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (InternalAttribute *)calloc(1, sizeof(InternalAttribute));
  *(InternalAttribute **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttrOperation_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  InternalAttrOperation *arg1 = (InternalAttrOperation *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttrOperation **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttrOperation_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  InternalAttrOperation *arg1 = (InternalAttrOperation *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttrOperation **)&jarg1; 
  result = (int) ((arg1)->type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttrOperation_1attribute_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_) {
  InternalAttrOperation *arg1 = (InternalAttrOperation *) 0 ;
  InternalAttribute *arg2 = (InternalAttribute *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(InternalAttrOperation **)&jarg1; 
  arg2 = *(InternalAttribute **)&jarg2; 
  if (arg1) (arg1)->attribute = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalAttrOperation_1attribute_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  InternalAttrOperation *arg1 = (InternalAttrOperation *) 0 ;
  InternalAttribute *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalAttrOperation **)&jarg1; 
  result = (InternalAttribute *) ((arg1)->attribute);
  *(InternalAttribute **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1InternalAttrOperation(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  InternalAttrOperation *arg1 = (InternalAttrOperation *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalAttrOperation **)&jarg1; 
  delete_InternalAttrOperation(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1InternalAttrOperation(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  InternalAttrOperation *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (InternalAttrOperation *)calloc(1, sizeof(InternalAttrOperation));
  *(InternalAttrOperation **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1attributeName_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->attributeName) free((char *)arg1->attributeName);
    if (arg2) {
      arg1->attributeName = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->attributeName, (const char *)arg2);
    } else {
      arg1->attributeName = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1attributeName_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  result = (char *) ((arg1)->attributeName);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1type_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->type = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1type_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  result = (int) ((arg1)->type);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1oper_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->oper = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1oper_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  result = (int) ((arg1)->oper);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1length_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->length = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1length_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  result = (int) ((arg1)->length);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1operand_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->operand) free((char *)arg1->operand);
    if (arg2) {
      arg1->operand = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->operand, (const char *)arg2);
    } else {
      arg1->operand = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1operand_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  result = (char *) ((arg1)->operand);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1conditions_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  struct InternalCondition **arg2 = (struct InternalCondition **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  arg2 = *(struct InternalCondition ***)&jarg2; 
  if (arg1) (arg1)->conditions = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_InternalCondition_1conditions_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  struct InternalCondition **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(InternalCondition **)&jarg1; 
  result = (struct InternalCondition **) ((arg1)->conditions);
  *(struct InternalCondition ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1InternalCondition(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  InternalCondition *arg1 = (InternalCondition *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalCondition **)&jarg1; 
  delete_InternalCondition(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1InternalCondition(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  InternalCondition *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (InternalCondition *)calloc(1, sizeof(InternalCondition));
  *(InternalCondition **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1id_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  sqlite3_int64 arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  arg2 = (sqlite3_int64)jarg2; 
  if (arg1) (arg1)->id = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1id_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  sqlite3_int64 result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  result = (sqlite3_int64) ((arg1)->id);
  jresult = (jlong)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1path_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->path) free((char *)arg1->path);
    if (arg2) {
      arg1->path = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->path, (const char *)arg2);
    } else {
      arg1->path = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1path_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  result = (char *) ((arg1)->path);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1name_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  char *arg2 = (char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return ;
  }
  {
    if (arg1->name) free((char *)arg1->name);
    if (arg2) {
      arg1->name = (char *) malloc(strlen((const char *)arg2)+1);
      strcpy((char *)arg1->name, (const char *)arg2);
    } else {
      arg1->name = 0;
    }
  }
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
}


SWIGEXPORT jstring JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1name_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jstring jresult = 0 ;
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  result = (char *) ((arg1)->name);
  if (result) jresult = (*jenv)->NewStringUTF(jenv, (const char *)result);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1content_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jbyteArray jarg2) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  signed char *arg2 = (signed char *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  {
    arg2 = (signed char *)(*jenv)->GetByteArrayElements(jenv, jarg2, 0);
  }
  if (arg1) (arg1)->content = arg2;
}


SWIGEXPORT jbyteArray JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1content_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jbyteArray jresult = 0 ;
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  signed char *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  result = (signed char *) ((arg1)->content);
  {
    jresult = (*jenv)->NewByteArray(jenv, arg1->contentLength);
    (*jenv)->SetByteArrayRegion(jenv, jresult, 0, arg1->contentLength, result);
  }
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1attributes_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  InternalAttribute **arg2 = (InternalAttribute **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  arg2 = *(InternalAttribute ***)&jarg2; 
  if (arg1) (arg1)->attributes = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1attributes_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  InternalAttribute **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  result = (InternalAttribute **) ((arg1)->attributes);
  *(InternalAttribute ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1attr_1count_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->attr_count = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_subSearchResult_1attr_1count_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(subSearchResult **)&jarg1; 
  result = (int) ((arg1)->attr_count);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1subSearchResult(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  subSearchResult *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (subSearchResult *)calloc(1, sizeof(subSearchResult));
  *(subSearchResult **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1subSearchResult(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  subSearchResult *arg1 = (subSearchResult *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(subSearchResult **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1SearchReturn(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SearchReturn **)&jarg1; 
  delete_SearchReturn(arg1);
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1hasMore_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->hasMore = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1hasMore_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  result = (int) ((arg1)->hasMore);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1data_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  subSearchResult **arg2 = (subSearchResult **) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  arg2 = *(subSearchResult ***)&jarg2; 
  if (arg1) (arg1)->data = arg2;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1data_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jlong jresult = 0 ;
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  subSearchResult **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  result = (subSearchResult **) ((arg1)->data);
  *(subSearchResult ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1size_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->size = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1size_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  result = (int) ((arg1)->size);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1allocated_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->allocated = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1allocated_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  result = (int) ((arg1)->allocated);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1result_1set(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int arg2 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  arg2 = (int)jarg2; 
  if (arg1) (arg1)->result = arg2;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SearchReturn_1result_1get(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  result = (int) ((arg1)->result);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1SearchReturn(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  SearchReturn *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (SearchReturn *)calloc(1, sizeof(SearchReturn));
  *(SearchReturn **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1SqliteDB(JNIEnv *jenv, jclass jcls) {
  jlong jresult = 0 ;
  SqliteDB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  result = (SqliteDB *)calloc(1, sizeof(SqliteDB));
  *(SqliteDB **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1SqliteDB(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(SqliteDB **)&jarg1; 
  free((char *) arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SqliteOpen(JNIEnv *jenv, jclass jcls, jstring jarg1) {
  jlong jresult = 0 ;
  char *arg1 = (char *) 0 ;
  SqliteDB *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = 0;
  if (jarg1) {
    arg1 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg1, 0);
    if (!arg1) return 0;
  }
  result = (SqliteDB *)SqliteOpen((char const *)arg1);
  *(SqliteDB **)&jresult = result; 
  if (arg1) (*jenv)->ReleaseStringUTFChars(jenv, jarg1, (const char *)arg1);
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_SqliteClose(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  SqliteClose(arg1);
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_activate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  result = (int)activate(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_deactivate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  result = (int)deactivate(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_checkDBVersion(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2, jintArray jarg3) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int *arg2 = (int *) 0 ;
  int *arg3 = (int *) 0 ;
  int temp2 ;
  int temp3 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  {
    if (!jarg3) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg3) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg3 = &temp3; 
  }
  result = (int)checkDBVersion(arg1,arg2,arg3);
  jresult = (jint)result; 
  {
    jint jvalue = (jint)temp2;
    (*jenv)->SetIntArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  {
    jint jvalue = (jint)temp3;
    (*jenv)->SetIntArrayRegion(jenv, jarg3, 0, 1, &jvalue);
  }
  
  
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_sqliteRetrieve(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jlong jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  sqlite3_int64 arg4 ;
  InternalCondition *arg5 = (InternalCondition *) 0 ;
  SearchReturn *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg5_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (sqlite3_int64)jarg4; 
  arg5 = *(InternalCondition **)&jarg5; 
  result = (SearchReturn *)sqliteRetrieve(arg1,arg2,(char const *)arg3,arg4,arg5);
  *(SearchReturn **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_sqliteCreate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jbyteArray jarg4, jint jarg5, jlong jarg6, jint jarg7, jlongArray jarg8) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  unsigned char *arg4 = (unsigned char *) 0 ;
  int arg5 ;
  InternalAttribute **arg6 = (InternalAttribute **) 0 ;
  int arg7 ;
  sqlite3_int64 *arg8 = (sqlite3_int64 *) 0 ;
  sqlite3_int64 temp8 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  {
    arg4 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg4, 0); 
  }
  arg5 = (int)jarg5; 
  arg6 = *(InternalAttribute ***)&jarg6; 
  arg7 = (int)jarg7; 
  {
    if (!jarg8) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg8) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg8 = &temp8; 
  }
  result = (int)sqliteCreate(arg1,arg2,(char const *)arg3,(unsigned char const *)arg4,arg5,arg6,arg7,arg8);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg4, (jbyte *) arg4, 0); 
  }
  {
    jlong jvalue = (jlong)temp8;
    (*jenv)->SetLongArrayRegion(jenv, jarg8, 0, 1, &jvalue);
  }
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_sqliteUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jlong jarg4, jbyteArray jarg5, jint jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  sqlite3_int64 arg4 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  int arg6 ;
  InternalAttribute **arg7 = (InternalAttribute **) 0 ;
  int arg8 ;
  InternalCondition *arg9 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg9_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (sqlite3_int64)jarg4; 
  {
    arg5 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg5, 0); 
  }
  arg6 = (int)jarg6; 
  arg7 = *(InternalAttribute ***)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(InternalCondition **)&jarg9; 
  result = (int)sqliteUpdate(arg1,arg2,(char const *)arg3,arg4,(unsigned char const *)arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg5, (jbyte *) arg5, 0); 
  }
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_sqliteDeleteCascade(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jlong jarg4, jint jarg5, jlong jarg6, jobject jarg6_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  sqlite3_int64 arg4 ;
  int arg5 ;
  InternalCondition *arg6 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg6_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (sqlite3_int64)jarg4; 
  arg5 = (int)jarg5; 
  arg6 = *(InternalCondition **)&jarg6; 
  result = (int)sqliteDeleteCascade(arg1,arg2,(char const *)arg3,arg4,arg5,arg6);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_sqliteDeleteExact(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jlong jarg4, jlong jarg5, jobject jarg5_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  sqlite3_int64 arg4 ;
  InternalCondition *arg5 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg5_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (sqlite3_int64)jarg4; 
  arg5 = *(InternalCondition **)&jarg5; 
  result = (int)sqliteDeleteExact(arg1,arg2,(char const *)arg3,arg4,arg5);
  jresult = (jint)result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_search(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jint jarg4, jlong jarg5, jobject jarg5_, jint jarg6, jint jarg7, jint jarg8, jobjectArray jarg9, jint jarg10) {
  jlong jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  int arg4 ;
  InternalCondition *arg5 = (InternalCondition *) 0 ;
  int arg6 ;
  int arg7 ;
  int arg8 ;
  char **arg9 = (char **) 0 ;
  int arg10 ;
  jint size9 ;
  SearchReturn *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg5_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (int)jarg4; 
  arg5 = *(InternalCondition **)&jarg5; 
  arg6 = (int)jarg6; 
  arg7 = (int)jarg7; 
  arg8 = (int)jarg8; 
  {
    int i = 0;
    size9 = (*jenv)->GetArrayLength(jenv, jarg9);
    
    
    
    arg9 = (char **)calloc(size9+1, sizeof(char *));
    
    for (i = 0; i<size9; i++) {
      jstring j_string = (jstring)(*jenv)->GetObjectArrayElement(jenv, jarg9, i);
      const char *c_string = (*jenv)->GetStringUTFChars(jenv, j_string, 0);
      
      
      
      arg9[i] = (char *)calloc(strlen(c_string)+1, sizeof(const char *));
      
      strcpy(arg9[i], c_string);
      (*jenv)->ReleaseStringUTFChars(jenv, j_string, c_string);
      (*jenv)->DeleteLocalRef(jenv, j_string);
    }
    arg9[i] = 0;
  }
  arg10 = (int)jarg10; 
  result = (SearchReturn *)search(arg1,arg2,(char const *)arg3,arg4,arg5,arg6,arg7,arg8,arg9,arg10);
  *(SearchReturn **)&jresult = result; 
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  {
    int i;
    for (i=0; i<size9-1; i++)
    
    
    
    
    free(arg9[i]);
    free(arg9);
    
  }
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_sqlitePartialUpdate(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jlong jarg2, jobject jarg2_, jstring jarg3, jlong jarg4, jbyteArray jarg5, jint jarg6, jlong jarg7, jint jarg8, jlong jarg9, jobject jarg9_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  ConfigList *arg2 = (ConfigList *) 0 ;
  char *arg3 = (char *) 0 ;
  sqlite3_int64 arg4 ;
  unsigned char *arg5 = (unsigned char *) 0 ;
  int arg6 ;
  InternalAttrOperation **arg7 = (InternalAttrOperation **) 0 ;
  int arg8 ;
  InternalCondition *arg9 = (InternalCondition *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  (void)jarg2_;
  (void)jarg9_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = *(ConfigList **)&jarg2; 
  arg3 = 0;
  if (jarg3) {
    arg3 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg3, 0);
    if (!arg3) return 0;
  }
  arg4 = (sqlite3_int64)jarg4; 
  {
    arg5 = (char *) (*jenv)->GetByteArrayElements(jenv, jarg5, 0); 
  }
  arg6 = (int)jarg6; 
  arg7 = *(InternalAttrOperation ***)&jarg7; 
  arg8 = (int)jarg8; 
  arg9 = *(InternalCondition **)&jarg9; 
  result = (int)sqlitePartialUpdate(arg1,arg2,arg3,arg4,(unsigned char const *)arg5,arg6,arg7,arg8,arg9);
  jresult = (jint)result; 
  {
    (*jenv)->ReleaseByteArrayElements(jenv, jarg5, (jbyte *) arg5, 0); 
  }
  if (arg3) (*jenv)->ReleaseStringUTFChars(jenv, jarg3, (const char *)arg3);
  
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_freeSearchReturn(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  SearchReturn *arg1 = (SearchReturn *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SearchReturn **)&jarg1; 
  freeSearchReturn(arg1);
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_beginTransaction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  result = (int)beginTransaction(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_commitTransaction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  result = (int)commitTransaction(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_rollbackTransaction(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  result = (int)rollbackTransaction(arg1);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_executeSqlStatementWithOutParameters(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jstring jarg2) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  char *arg2 = (char *) 0 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = 0;
  if (jarg2) {
    arg2 = (char *)(*jenv)->GetStringUTFChars(jenv, jarg2, 0);
    if (!arg2) return 0;
  }
  result = (int)executeSqlStatementWithOutParameters(arg1,arg2);
  jresult = (jint)result; 
  if (arg2) (*jenv)->ReleaseStringUTFChars(jenv, jarg2, (const char *)arg2);
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_getFreeListCount(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int *arg2 = (int *) 0 ;
  int temp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (int)getFreeListCount(arg1,arg2);
  jresult = (jint)result; 
  {
    jint jvalue = (jint)temp2;
    (*jenv)->SetIntArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_getPageCount(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jintArray jarg2) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int *arg2 = (int *) 0 ;
  int temp2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  {
    if (!jarg2) {
      SWIG_JavaThrowException(jenv, SWIG_JavaNullPointerException, "array null");
      return 0;
    }
    if ((*jenv)->GetArrayLength(jenv, jarg2) == 0) {
      SWIG_JavaThrowException(jenv, SWIG_JavaIndexOutOfBoundsException, "Array must contain at least 1 element");
      return 0;
    }
    arg2 = &temp2; 
  }
  result = (int)getPageCount(arg1,arg2);
  jresult = (jint)result; 
  {
    jint jvalue = (jint)temp2;
    (*jenv)->SetIntArrayRegion(jenv, jarg2, 0, 1, &jvalue);
  }
  
  return jresult;
}


SWIGEXPORT jint JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_setMaxPageCount(JNIEnv *jenv, jclass jcls, jlong jarg1, jobject jarg1_, jint jarg2) {
  jint jresult = 0 ;
  SqliteDB *arg1 = (SqliteDB *) 0 ;
  int arg2 ;
  int result;
  
  (void)jenv;
  (void)jcls;
  (void)jarg1_;
  arg1 = *(SqliteDB **)&jarg1; 
  arg2 = (int)jarg2; 
  result = (int)setMaxPageCount(arg1,arg2);
  jresult = (jint)result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_search_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  subSearchResult **arg1 = (subSearchResult **) 0 ;
  int arg2 ;
  subSearchResult *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(subSearchResult ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (subSearchResult *)search_array_getitem(arg1,arg2);
  *(subSearchResult **)&jresult = result; 
  return jresult;
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1attribute_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  InternalAttribute **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (InternalAttribute **)new_attribute_array(arg1);
  *(InternalAttribute ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1attribute_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  InternalAttribute **arg1 = (InternalAttribute **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalAttribute ***)&jarg1; 
  delete_attribute_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_attribute_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  InternalAttribute **arg1 = (InternalAttribute **) 0 ;
  int arg2 ;
  InternalAttribute *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalAttribute ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (InternalAttribute *)attribute_array_getitem(arg1,arg2);
  *(InternalAttribute **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_attribute_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jobject jarg3_) {
  InternalAttribute **arg1 = (InternalAttribute **) 0 ;
  int arg2 ;
  InternalAttribute *arg3 = (InternalAttribute *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(InternalAttribute ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(InternalAttribute **)&jarg3; 
  attribute_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1operation_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  InternalAttrOperation **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (InternalAttrOperation **)new_operation_array(arg1);
  *(InternalAttrOperation ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1operation_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  InternalAttrOperation **arg1 = (InternalAttrOperation **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalAttrOperation ***)&jarg1; 
  delete_operation_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_operation_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  InternalAttrOperation **arg1 = (InternalAttrOperation **) 0 ;
  int arg2 ;
  InternalAttrOperation *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalAttrOperation ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (InternalAttrOperation *)operation_array_getitem(arg1,arg2);
  *(InternalAttrOperation **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_operation_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jobject jarg3_) {
  InternalAttrOperation **arg1 = (InternalAttrOperation **) 0 ;
  int arg2 ;
  InternalAttrOperation *arg3 = (InternalAttrOperation *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(InternalAttrOperation ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(InternalAttrOperation **)&jarg3; 
  operation_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1configItem_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  ConfigItem **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (ConfigItem **)new_configItem_array(arg1);
  *(ConfigItem ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1configItem_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  ConfigItem **arg1 = (ConfigItem **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ConfigItem ***)&jarg1; 
  delete_configItem_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_configItem_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  ConfigItem **arg1 = (ConfigItem **) 0 ;
  int arg2 ;
  ConfigItem *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(ConfigItem ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (ConfigItem *)configItem_array_getitem(arg1,arg2);
  *(ConfigItem **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_configItem_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jobject jarg3_) {
  ConfigItem **arg1 = (ConfigItem **) 0 ;
  int arg2 ;
  ConfigItem *arg3 = (ConfigItem *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(ConfigItem ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(ConfigItem **)&jarg3; 
  configItem_array_setitem(arg1,arg2,arg3);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_new_1condition_1array(JNIEnv *jenv, jclass jcls, jint jarg1) {
  jlong jresult = 0 ;
  int arg1 ;
  InternalCondition **result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = (int)jarg1; 
  result = (InternalCondition **)new_condition_array(arg1);
  *(InternalCondition ***)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_delete_1condition_1array(JNIEnv *jenv, jclass jcls, jlong jarg1) {
  InternalCondition **arg1 = (InternalCondition **) 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalCondition ***)&jarg1; 
  delete_condition_array(arg1);
}


SWIGEXPORT jlong JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_condition_1array_1getitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2) {
  jlong jresult = 0 ;
  InternalCondition **arg1 = (InternalCondition **) 0 ;
  int arg2 ;
  InternalCondition *result = 0 ;
  
  (void)jenv;
  (void)jcls;
  arg1 = *(InternalCondition ***)&jarg1; 
  arg2 = (int)jarg2; 
  result = (InternalCondition *)condition_array_getitem(arg1,arg2);
  *(InternalCondition **)&jresult = result; 
  return jresult;
}


SWIGEXPORT void JNICALL Java_com_actility_m2m_storage_driver_sqlite_impl_sqlitedriverJNI_condition_1array_1setitem(JNIEnv *jenv, jclass jcls, jlong jarg1, jint jarg2, jlong jarg3, jobject jarg3_) {
  InternalCondition **arg1 = (InternalCondition **) 0 ;
  int arg2 ;
  InternalCondition *arg3 = (InternalCondition *) 0 ;
  
  (void)jenv;
  (void)jcls;
  (void)jarg3_;
  arg1 = *(InternalCondition ***)&jarg1; 
  arg2 = (int)jarg2; 
  arg3 = *(InternalCondition **)&jarg3; 
  condition_array_setitem(arg1,arg2,arg3);
}


#ifdef __cplusplus
}
#endif

