/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_actility_m2m_shutdown_hook_jni_impl_JShutdownHook */

#ifndef _Included_com_actility_m2m_shutdown_hook_jni_impl_JShutdownHook
#define _Included_com_actility_m2m_shutdown_hook_jni_impl_JShutdownHook
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_actility_m2m_shutdown_hook_jni_impl_JShutdownHook
 * Method:    setSignalHandler
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_actility_m2m_shutdown_hook_jni_impl_JShutdownHook_setSignalHandler
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
